### PR TITLE
Add qwertz keyboard layout

### PR DESCRIPTION
**Pull request by patricksadowski**
While you are still typing with a familiar keyboard layout you get in
touch with the special layers of neo.

### CODE REVIEW

**Comment by MaxGyver83** [comment]
Sorry for my late reaction. I didn't get a notification about your pull request. I'll test this later today (I'm in Linux now).

**Comment by MaxGyver83** [comment]
I just have tested your branch/your QWERTZ variant. It works as expected. The only problem is that the "ß" is missing in that layout. We need to find a place for it. Maybe on the "+" key. Or like in the classic QWERTZ next to "0".

**Comment by patricksadowski** [comment]
Because QWERTZ is a german layout I placed it next to "0".

**Comment by patricksadowski** [comment]
I think you should review your notification preferences 😁

**Comment by MaxGyver83** [comment]
> Because QWERTZ is a german layout I placed it next to "0".

Good choice!

> I think you should review your notification preferences 😁

This time I have received an e-mail. I just postponed testing/merging your commit. 😉 Sorry for the delay.

Thanks for your contribution! 🎉

**Pull request merged**
