### PR TITLE
Fixes an issue with UTF8 characters in settings

### PR DESCRIPTION
**Pull request by FL550**
This makes it possible to use ö as input to ModTap

### CODE REVIEW

**Comment by MaxGyver83** [comment]
Thank you for this PR!

**Comment by FL550** [comment]
I have to give this back to you. Thank you very much for this tool!

**Comment by FL550** [comment]
And by the way, thanks again for the vou layout 😉

**Comment by MaxGyver83** [comment]
My pleasure :smile:

**Pull request merged**
